//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tecnoservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID { get; set; }
        public int Equipment_id { get; set; }
        public int Fault_type_id { get; set; }
        public int Client_id { get; set; }
        public Nullable<int> Executor_id { get; set; }
        public string Comments { get; set; }
        public string Description { get; set; }
        public System.DateTime Date_add { get; set; } = DateTime.Now;
        public Nullable<System.DateTime> Date_end { get; set; }
        public int Status_id { get; set; }


        public TimeSpan? ExecutionTime { get; set; }

        public virtual Equipment Equipment { get; set; }
        public virtual Fault_type Fault_type { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
